float64[3] tauFeedForward
float64[3] forceFeedForward
float64[3] qDes
float64[3] qdDes
float64[3] pDes
float64[3] vDes
float64[3] pAct
float64[3] vAct
float64[3] pError
float64[3] vError
float64[3] kpCartesian # Элементы главной диагонали матрицы Kp
float64[3] kdCartesian # Элементы главной диагонали матрицы Kd
float64[3] kpJoint # Элементы главной диагонали матрицы Kp
float64[3] kdJoint # Элементы главной диагонали матрицы Kp
